# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: coffeebisquit example website
#email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  This is an example website for coffeebisquit.
baseurl: "" # the subpath of your site, e.g. /blog TODO/FIXME: support the baseurl and url properties correctly; coffeebisquit currently doesn't work right with them.
url: "" # the base hostname & protocol for your site, e.g. http://example.com
mastodon:
  - username: DrewNaylor
    instance: mastodon.online

# We have to say if comments are enabled on this website
# so that they can be turned on and off site-wide.
# Comments on the example website are turned off since I have no GTS instance for it yet.
comments-enabled: false

# gts-conduit is used to get comments from a GoToSocial instance.
#gts-conduit-instance: "http://localhost:4242"

# gts-instance is the GoToSocial instance used by the accounts on this website.
#gts-instance: "http://localhost:8080"

# Build settings
theme: coffeebisquit

# I use CommonMark for stuff like auto-linking
# NOTE: If you enable "DoPeertubeRedirects" in the peertube-imports script, you'll need the
#       "jekyll-redirect-from" plugin, and using it will make the Jekyll build time go up a lot
#       if you have a lot of pages to redirect unfortunately.
plugins:
  - jekyll-seo-tag
  - jekyll-commonmark
  - jekyll-redirect-from
markdown: CommonMark

# Descriptions use HTML <br> items in them for line breaks which works even though the automated version looks bad,
# but you have to enable "UNSAFE" for commonmark in your _config.yml:
# https://github.com/jekyll/jekyll-commonmark/issues/24#issuecomment-460695465
commonmark:
  options: ["UNSAFE"]
  extensions: ["strikethrough", "autolink"]
  
# jekyll-archives:
#   enabled: all
#   layouts:
#     year: archive/year
#     month: archive/month
#     day: archive/day
#     tag: archive/tag
#     category: archive/category-page
#   permalinks:
#     year: '/:year/'
#     month: '/:year/:month/'
#     day: '/:year/:month/:day/'
#     tag: '/tags/:name/'
#     category: '/category/:name/'
  
# Collections for channels and playlists:
# see: https://jekyllrb.com/docs/collections/
# Playlists have a permalink format to make them more predictable
# and that uses the "slug" property in the playlist file.
# see here: https://jekyllrb.com/docs/permalinks/#collections
collections:
  channels:
    output: true
  playlists:
    output: true
    permalink: /:collection/:title
  categories:
    output: true
    
# Set defaults for collections:
# https://jekyllhub.com/tutorial/2026/02/04/jekyll-collections-guide/
# NOTE: by setting each category to default to the "category-page"
#       layout, this allows each category file to only have to have
#       its filename be set in order to have a new or renamed category
#       since each category uses the "slug", or the part of the filename
#       without the extension and the rest of the path, to see if it's
#       the correct category to show a given video.
defaults:
  - scope:
      path: ""
      type: "categories"
    values:
      layout: "category-page"

# Using jekyll-archives for categories, tags, and date-based archives.
# See: https://stackoverflow.com/a/48357942 under CC BY-SA 3.0 and https://github.com/jekyll/jekyll-archives
# Actually, this is way too complicated and puts the tags in the top bar so that's a problem.
# I'd still like to do this eventually, it's just too confusing right now.
# TODO: fork the jekyll-archives plugin to add video-related stuff to it so that "video-category" can be used, for example.
# plugins:
  # - jekyll-archives

# jekyll-archives:
#   enabled: all
#   layouts:
#     year: archive/year
#     month: archive/month
#     day: archive/day
#     tag: archive/tag
#     category: archive/category-page
#   permalinks:
#     year: '/:year/'
#     month: '/:year/:month/'
#     day: '/:year/:month/:day/'
#     tag: '/tags/:name/'
#     category: '/category/:name/'
  
# jekyll-archives:
#   enabled: all
#   layouts:
#     year: archive/year
#     month: archive/month
#     day: archive/day
#     tag: archive/tag
#     category: archive/category-page
#   permalinks:
#     year: '/:year/'
#     month: '/:year/:month/'
#     day: '/:year/:month/:day/'
#     tag: '/tags/:name/'
#     category: '/category/:name/'
  
